apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-k8-demo
spec:
  selector:
    matchLabels:
      app: spring-k8-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-k8-demo
    spec:
      containers:
        - name: spring-k8-demo
          image: openjdk:8
          ports:
          - containerPort: 5051              
            
---
apiVersion: v1
kind: Service
metadata:
  name: spring-k8-demo
spec:
  ports:
  - port: 5053
    targetPort: 5053
    protocol: TCP
    nodePort: 30603
  selector:
    app: spring-k8-demo
  type: NodePort